// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
// @flow

import keyMirror from 'utils/key_mirror';

export default keyMirror({
    LINK_GROUP_SYNCABLE_REQUEST: null,
    LINK_GROUP_SYNCABLE_SUCCESS: null,
    LINK_GROUP_SYNCABLE_FAILURE: null,
    LINKED_GROUP_TEAM: null,
    LINKED_GROUP_CHANNEL: null,

    UNLINK_GROUP_SYNCABLE_REQUEST: null,
    UNLINK_GROUP_SYNCABLE_SUCCESS: null,
    UNLINK_GROUP_SYNCABLE_FAILURE: null,
    UNLINKED_GROUP_TEAM: null,
    UNLINKED_GROUP_CHANNEL: null,

    GET_GROUP_SYNCABLES_REQUEST: null,
    GET_GROUP_SYNCABLES_SUCCESS: null,
    GET_GROUP_SYNCABLES_FAILURE: null,
    RECEIVED_GROUP_TEAMS: null,
    RECEIVED_GROUP_CHANNELS: null,

    GET_GROUP_MEMBERS_REQUEST: null,
    GET_GROUP_MEMBERS_SUCCESS: null,
    GET_GROUP_MEMBERS_FAILURE: null,
    RECEIVED_GROUP_MEMBERS: null,

    GET_GROUP_REQUEST: null,
    GET_GROUP_SUCCESS: null,
    GET_GROUP_FAILURE: null,
    RECEIVED_GROUP: null,

    RECEIVED_GROUPS: null,

    GET_GROUPS_ASSOCIATED_TO_TEAM_REQUEST: null,
    GET_GROUPS_ASSOCIATED_TO_TEAM_SUCCESS: null,
    GET_GROUPS_ASSOCIATED_TO_TEAM_FAILURE: null,
    RECEIVED_GROUPS_ASSOCIATED_TO_TEAM: null,

    GET_GROUPS_ASSOCIATED_TO_CHANNEL_REQUEST: null,
    GET_GROUPS_ASSOCIATED_TO_CHANNEL_SUCCESS: null,
    GET_GROUPS_ASSOCIATED_TO_CHANNEL_FAILURE: null,
    RECEIVED_GROUPS_ASSOCIATED_TO_CHANNEL: null,

    GET_ALL_GROUPS_ASSOCIATED_TO_TEAM_REQUEST: null,
    GET_ALL_GROUPS_ASSOCIATED_TO_TEAM_SUCCESS: null,
    GET_ALL_GROUPS_ASSOCIATED_TO_TEAM_FAILURE: null,
    RECEIVED_ALL_GROUPS_ASSOCIATED_TO_TEAM: null,

    GET_ALL_GROUPS_ASSOCIATED_TO_CHANNEL_REQUEST: null,
    GET_ALL_GROUPS_ASSOCIATED_TO_CHANNEL_SUCCESS: null,
    GET_ALL_GROUPS_ASSOCIATED_TO_CHANNEL_FAILURE: null,
    RECEIVED_ALL_GROUPS_ASSOCIATED_TO_CHANNEL: null,

    GET_GROUPS_NOT_ASSOCIATED_TO_TEAM_REQUEST: null,
    GET_GROUPS_NOT_ASSOCIATED_TO_TEAM_SUCCESS: null,
    GET_GROUPS_NOT_ASSOCIATED_TO_TEAM_FAILURE: null,
    RECEIVED_GROUPS_NOT_ASSOCIATED_TO_TEAM: null,

    GET_GROUPS_NOT_ASSOCIATED_TO_CHANNEL_REQUEST: null,
    GET_GROUPS_NOT_ASSOCIATED_TO_CHANNEL_SUCCESS: null,
    GET_GROUPS_NOT_ASSOCIATED_TO_CHANNEL_FAILURE: null,
    RECEIVED_GROUPS_NOT_ASSOCIATED_TO_CHANNEL: null,
});
