// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
import keyMirror from 'utils/key_mirror';

export default keyMirror({
    DELETE_INCOMING_HOOK_FAILURE: null,
    DELETE_OUTGOING_HOOK_FAILURE: null,
    REGEN_COMMAND_TOKEN_FAILURE: null,
    DELETE_COMMAND_FAILURE: null,
    GET_AUTHORIZED_OAUTH_APPS_FAILURE: null,
    DELETE_OAUTH_APP_FAILURE: null,
    SUBMIT_INTERACTIVE_DIALOG_FAILURE: null,

    DEAUTHORIZE_OAUTH_APP_SUCCESS: null,

    EXECUTE_COMMAND_SUCCESS: null,

    RECEIVED_INCOMING_HOOK: null,
    RECEIVED_INCOMING_HOOKS: null,
    DELETED_INCOMING_HOOK: null,
    RECEIVED_OUTGOING_HOOK: null,
    RECEIVED_OUTGOING_HOOKS: null,
    DELETED_OUTGOING_HOOK: null,
    RECEIVED_CUSTOM_TEAM_COMMANDS: null,
    RECEIVED_COMMAND: null,
    RECEIVED_COMMANDS: null,
    RECEIVED_COMMAND_TOKEN: null,
    DELETED_COMMAND: null,
    RECEIVED_OAUTH_APP: null,
    RECEIVED_OAUTH_APPS: null,
    DELETED_OAUTH_APP: null,

    RECEIVED_DIALOG_TRIGGER_ID: null,
    RECEIVED_DIALOG: null,
});
