// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
// @flow

export type Credentials = {|
    url: string,
    token: string,
|};

type WithLicense = {|
    IsLicensed: "true",
    Announcement: "true" | "false",
    Cluster: "true" | "false",
    Company: string,
    Compliance: "true" | "false",
    CustomPermissionsSchemes: "true" | "false",
    CustomTermsOfService: "true" | "false",
    DataRetention: "true" | "false",
    Elasticsearch: "true" | "false",
    Email: string,
    EmailNotificationContents: "true" | "false",
    ExpiresAt: string,
    GoogleOAuth: "true" | "false",
    Id: string,
    IssuedAt: string,
    LDAP: "true" | "false",
    MFA: "true" | "false",
    MHPNS: "true" | "false",
    MessageExport: "true" | "false",
    Metrics: "true" | "false",
    Name: string,
    Office365OAuth: "true" | "false",
    PhoneNumber: string,
    SAML: "true" | "false",
    SkuName: string,
    SkuShortName: string,
    StartsAt: string,
    Users: string,
|};

type WithoutLicense = {|
    IsLicensed: "false",
|}

export type License = WithLicense | WithoutLicense;

export type Config = {|
    AboutLink: string,
    AllowBannerDismissal: "true" | "false",
    AllowCustomThemes: "true" | "false",
    AllowedThemes: string,
    AndroidAppDownloadLink: string,
    AndroidLatestVersion: string,
    AndroidMinVersion: string,
    AppDownloadLink: string,
    AsymmetricSigningPublicKey: string,
    AvailableLocales: string,
    BannerColor: string,
    BannerText: string,
    BannerTextColor: string,
    BuildDate: string,
    BuildEnterpriseReady: "true" | "false",
    BuildHash: string,
    BuildHashEnterprise: string,
    BuildNumber: string,
    CloseUnusedDirectMessages: "true" | "false",
    CustomBrandText: string,
    CustomDescriptionText: string,
    CustomTermsOfServiceReAcceptancePeriod: string,
    CustomUrlSchemes: string,
    DataRetentionEnableFileDeletion: "true" | "false",
    DataRetentionEnableMessageDeletion: "true" | "false",
    DataRetentionFileRetentionDays: string,
    DataRetentionMessageRetentionDays: string,
    DefaultClientLocale: string,
    DefaultTheme: string,
    DesktopLatestVersion: string,
    DesktopMinVersion: string,
    DiagnosticId: string,
    DiagnosticsEnabled: "true" | "false",
    EmailLoginButtonBorderColor: string,
    EmailLoginButtonColor: string,
    EmailLoginButtonTextColor: string,
    EmailNotificationContentsType: string,
    EnableBanner: "true" | "false",
    EnableChannelViewedMessages: "true" | "false",
    EnableCluster: "true" | "false",
    EnableCommands: "true" | "false",
    EnableCompliance: "true" | "false",
    EnableConfirmNotificationsToChannel: "true" | "false",
    EnableCustomBrand: "true" | "false",
    EnableCustomEmoji: "true" | "false",
    EnableCustomTermsOfService: "true" | "false",
    EnableDeveloper: "true" | "false",
    EnableDiagnostics: "true" | "false",
    EnableEmailBatching: "true" | "false",
    EnableEmailInvitations: "true" | "false",
    EnableEmojiPicker: "true" | "false",
    EnableFileAttachments: "true" | "false",
    EnableGifPicker: "true" | "false",
    EnableIncomingWebhooks: "true" | "false",
    EnableLdap: "true" | "false",
    EnableLinkPreviews: "true" | "false",
    EnableMetrics: "true" | "false",
    EnableMobileFileDownload: "true" | "false",
    EnableMobileFileUpload: "true" | "false",
    EnableMultifactorAuthentication: "true" | "false",
    EnableOAuthServiceProvider: "true" | "false",
    EnableOpenServer: "true" | "false",
    EnableOutgoingWebhooks: "true" | "false",
    EnablePostIconOverride: "true" | "false",
    EnablePostUsernameOverride: "true" | "false",
    EnablePreviewFeatures: "true" | "false",
    EnablePreviewModeBanner: "true" | "false",
    EnablePublicLink: "true" | "false",
    EnableSaml: "true" | "false",
    EnableSignInWithEmail: "true" | "false",
    EnableSignInWithUsername: "true" | "false",
    EnableSignUpWithEmail: "true" | "false",
    EnableSignUpWithGitLab: "true" | "false",
    EnableSignUpWithGoogle: "true" | "false",
    EnableSignUpWithOffice365: "true" | "false",
    EnableTesting: "true" | "false",
    EnableThemeSelection: "true" | "false",
    EnableTutorial: "true" | "false",
    EnableUserAccessTokens: "true" | "false",
    EnableUserCreation: "true" | "false",
    EnableUserDeactivation: "true" | "false",
    EnableUserTypingMessages: "true" | "false",
    EnableXToLeaveChannelsFromLHS: "true" | "false",
    EnforceMultifactorAuthentication: "true" | "false",
    ExperimentalChannelOrganization: "true" | "false",
    ExperimentalClientSideCertCheck: string,
    ExperimentalClientSideCertEnable: "true" | "false",
    ExperimentalEnableAuthenticationTransfer: "true" | "false",
    ExperimentalEnableAutomaticReplies: "true" | "false",
    ExperimentalEnableDefaultChannelLeaveJoinMessages: "true" | "false",
    ExperimentalEnablePostMetadata: "true" | "false",
    ExperimentalGroupUnreadChannels: string,
    ExperimentalHideTownSquareinLHS: "true" | "false",
    ExperimentalPrimaryTeam: string,
    ExperimentalTimezone: "true" | "false",
    ExperimentalTownSquareIsReadOnly: "true" | "false",
    ExperimentalViewArchivedChannels: "true" | "false",
    GfycatApiKey: string,
    GfycatApiSecret: string,
    GoogleDeveloperKey: string,
    HasImageProxy: "true" | "false",
    HelpLink: string,
    InstallationDate: string,
    IosAppDownloadLink: string,
    IosLatestVersion: string,
    IosMinVersion: string,
    LdapFirstNameAttributeSet: "true" | "false",
    LdapLastNameAttributeSet: "true" | "false",
    LdapLoginButtonBorderColor: string,
    LdapLoginButtonColor: string,
    LdapLoginButtonTextColor: string,
    LdapLoginFieldName: string,
    LdapNicknameAttributeSet: "true" | "false",
    MaxFileSize: string,
    MaxNotificationsPerChannel: string,
    MaxPostSize: string,
    NoAccounts: "true" | "false",
    PasswordMinimumLength: string,
    PasswordRequireLowercase: "true" | "false",
    PasswordRequireNumber: "true" | "false",
    PasswordRequireSymbol: "true" | "false",
    PasswordRequireUppercase: "true" | "false",
    PluginsEnabled: "true" | "false",
    PostEditTimeLimit: string,
    PrivacyPolicyLink: string,
    ReportAProblemLink: string,
    RequireEmailVerification: "true" | "false",
    RestrictDirectMessage: string,
    RunJobs: "true" | "false",
    SQLDriverName: string,
    SamlFirstNameAttributeSet: "true" | "false",
    SamlLastNameAttributeSet: "true" | "false",
    SamlLoginButtonBorderColor: string,
    SamlLoginButtonColor: string,
    SamlLoginButtonText: string,
    SamlLoginButtonTextColor: string,
    SamlNicknameAttributeSet: "true" | "false",
    SendEmailNotifications: "true" | "false",
    SendPushNotifications: "true" | "false",
    ShowEmailAddress: "true" | "false",
    SiteName: string,
    SiteURL: string,
    SupportEmail: string,
    TeammateNameDisplay: string,
    TermsOfServiceLink: string,
    TimeBetweenUserTypingUpdatesMilliseconds: string,
    Version: string,
    WebsocketPort: string,
    WebsocketSecurePort: string,
    WebsocketURL: string,
|};

export type DataRetentionPolicy = {|
    message_deletion_enabled: boolean,
    file_deletion_enabled: boolean,
    message_retention_cutoff: number,
    file_retention_cutoff: number,
|};

export type GeneralState = {|
    appState: boolean,
    credentials: ?Credentials,
    config: ?Config,
    dataRetentionPolicy: ?DataRetentionPolicy,
    deviceToken: string,
    license: License,
    serverVersion: string,
    timezones: Array<string>
|};
